// import "./solutions/day1.js";
// import "./solutions/day2.js";
// import "./solutions/day3.js";
// import "./solutions/day4.js";
// import "./solutions/day5.js";
// import "./solutions/day6.js";
// import "./solutions/day7.js";
// import "./solutions/day8.js";
// import "./solutions/day9.js";
// import "./solutions/day10.js";
// import "./solutions/day11.js";
// import "./solutions/day12.js";
import "./solutions/day13.js";
